### ISSUE TITLE
Fix italics

### ISSUE THREAD

**Issue by Gragt** [jdecock/hugh-lofting_the-voyages-of-doctor-dolittle#5]
Chapter 1-12, line 15: The chart name should be quoted without italics and semantic inflection since it is part of an atlas, i.e., a larger work.
Chapter 1-12, line 21: “A.B.C.” doesn’t appear to be emphasised. If it isn’t, it shouldn’t be italicised at all.
Chapter 3-5, line 30: The quote isn’t really Latin. Gibberish like that should be unsemanticated italic.
Chapter 4-2, line 34: The writing on the signs doesn’t appear to be inner thoughts. It doesn’t look emphasised either, so they should probably be left as unsemanticated `<i>`s.
Chapter 4-7, line 63: Individual “Boom!” should be italicised separately but not the ellipses.

**Comment by jdecock** [comment]
- "A.B.C." is italicized in the source. Reading that line I can see a case for emphasis but it could go either way.

**Comment by Gragt** [comment]
I saw it was italicised in the source but, reading it out loud, it doesn’t appear to be emphasised. In this case, [the rule is not to italicise it at all](https://standardebooks.org/manual/1.6.4/8-typography#8.2.8.2).

I would remove the italics there, but what do you think?

**Comment by jdecock** [comment]
I've gone ahead and removed it.
