### ISSUE TITLE
[Suggestion] Update SE subject to upcoming standard

### ISSUE THREAD

**Issue by Gragt** [jdecock/hugh-lofting_the-voyages-of-doctor-dolittle#6]
content.opf: You can add an apostrophe to “Childrens”, changing it to “Children’s”—it is an [upcoming change to the manual](https://github.com/standardebooks/manual/commit/a37b9ae68755a1e9f7f662fe95cc064e433713c5) and existing books have already received it.

**Comment by jdecock** [comment]
I've made that change, but `se lint` fails now.

**Comment by Gragt** [comment]
That’s okay: all checks pass in the development version of the toolset.
