### ISSUE TITLE
Fix collection types

### ISSUE THREAD

**Issue by Gragt** [jdecock/hugh-lofting_the-voyages-of-doctor-dolittle#7]
content.opf: Collection types appear to be inverted: the Newbery Medal is expected to receive a new entry each year so it should be a series, but Doctor Dolittle can be considered finite and thus should be a set.

**Comment by jdecock** [comment]
I don't think this is the way that these have been used in the past. For instance, see [The Murder of Roger Ackroyd](https://github.com/standardebooks/agatha-christie_the-murder-of-roger-ackroyd/blob/master/src/epub/content.opf) that Vince and Alex produced. It's using set and series the way that I've got them.

**Comment by Gragt** [comment]
It is a tricky one. :)

The [EPUB spec document](https://www.w3.org/publishing/epub32/epub-packages.html#sec-collection-type) gives some information, definitions, and, more importantly, examples.

The main thing to take away from a series is that is open-ended with works expected to be issued over time. A set, on the other hand, is considered finite and could be packaged and sold as a whole. The document gives a magazine as example of a series, and *The Lord of the Rings* and *Harry Potter* as examples of sets.

In *The Murder of Roger Ackroyd*, the collection “Le Monde’s 100 Books of the Century” works a set because it is finite: there are 100 entries and we do not expect any more to be added. The *Poirot* collection could be argued about: if we only consider Poirot stories written by Agatha Christie, it should also be a set, but if we are talking of Poirot in general, with new stories written by Sophie Hannah, it may be more appropriate to classify it as series.

In this case, the Newbery Medal collection is expected to get a new entry every year with no end in sight; that would fit the description of a series. *Doctor Dolittle*, on the other hand isn’t receiving new entries (to the best of my knowledge), can be considered finite, and could be packaged and sold as a unit; that would fit the set description.

**Comment by jdecock** [comment]
I'm not saying that you're wrong about how the EPUB spec describes it, just that it doesn't seem to be how it's used in everything else. For instance, all the Pulitzer Prize Winners are listed as a set despite it being an ongoing thing and every single series I've checked (Sherlock Holmes, Anne of Green Gables, Wizard of Oz, etc.) are all listed as a series.

**Comment by Gragt** [comment]
It seems to be a bit of a grey area on SE, and in some cases there could be arguments for either option. It isn’t really something that has come up often on the mailing list and Alex hasn’t said much on the topic—except to check the EPUB spec as far as I can tell. Maybe a more in-depth discussion on the topic will come up later.

Being the producer, it’s ultimately your call. Worst-case scenario: Alex can decide to make the change himself before release if he deems it necessary. We also have the option to ask Alex to look at this and decide for us—final say is his, after all.

The only thing I ask is for you to consider this: in rule vs usage, the SE project tends to favour rules. That’s why we produce EPUB files that no ereader can currently display; the files must instead be converted to compatible formats. Right now, it doesn’t seem that picking set or series is a big thing, but it might become important later and require the whole corpus to be checked. With this in mind, I find it prudent to follow the EPUB spec—it has worked so far.

I’ll respect your decision. If you want to close this without any changes, fair enough.

**Comment by jdecock** [comment]
I'm going to close this here and I'll post a separate thread on the group to discuss further.
